name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * 0" # آپدیت هفتگی
  workflow_dispatch: # اجرا دستی

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: mohammadhosseinmoeinzadeh
